// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ts.Api.Infrastructure.Persistence;

#nullable disable

namespace Ts.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905021008_AddFrozenStockManagement")]
    partial class AddFrozenStockManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ts.Api.Domain.Catalog.CatalogOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FulfillmentMode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("catalog_offers", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Customers.CustomerDietaryRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Marker")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CustomerId", "Marker")
                        .IsUnique();

                    b.ToTable("customer_dietary_restrictions", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Finance.FinancialCreditMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OrderId")
                        .IsUnique()
                        .HasFilter("\"OrderId\" IS NOT NULL AND \"Type\" = 1");

                    b.HasIndex("OrganizationId", "CustomerId", "OccurredAt");

                    b.ToTable("financial_credit_movements", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("integer");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ProducibleItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ProducibleItemId");

                    b.HasIndex("OrganizationId", "OfferId", "ProducibleItemId", "Presentation")
                        .IsUnique();

                    b.ToTable("frozen_configurations", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<Guid>("FrozenConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("ManufacturedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "FrozenConfigurationId");

                    b.HasIndex("OrganizationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "ExpiresOn", "ManufacturedOn", "Id");

                    b.ToTable("frozen_lots", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenStockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrozenLotId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "FrozenLotId", "OccurredAt");

                    b.ToTable("frozen_stock_movements", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.DailyCapacity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastConfigurationIdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("OperationalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservedUnits")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "LastConfigurationIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "OperationalDate")
                        .IsUnique();

                    b.ToTable("daily_capacities", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.FrozenStockAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrozenConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrozenLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "FrozenConfigurationId");

                    b.HasIndex("OrganizationId", "FrozenLotId");

                    b.HasIndex("OrganizationId", "OrderId");

                    b.HasIndex("OrganizationId", "OrderItemId", "FrozenLotId")
                        .IsUnique();

                    b.ToTable("frozen_stock_allocations", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmationIdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreationIdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModificationIdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("OperationalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ConfirmationIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "CreationIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "LastModificationIdempotencyKey")
                        .IsUnique();

                    b.ToTable("orders", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OrderId");

                    b.ToTable("order_charges", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderConfirmationAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("FinancialCreditApplied")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlanCreditCoveredAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "OrderId");

                    b.ToTable("order_confirmation_audits", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FrozenConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FrozenPresentation")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("FulfillmentMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("OfferName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProducibleItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProducibleItemName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "FrozenConfigurationId");

                    b.HasIndex("OrganizationId", "OfferId");

                    b.HasIndex("OrganizationId", "OrderId");

                    b.HasIndex("OrganizationId", "ProducibleItemId");

                    b.ToTable("order_items", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderItemComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompositionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CompositionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("DietaryMarkers")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("TotalQuantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OrderId");

                    b.HasIndex("OrganizationId", "OrderItemId");

                    b.ToTable("order_item_components", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderLifecycleEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<int>("CapacityUnitsReleased")
                        .HasColumnType("integer");

                    b.Property<int>("ChargesCancelled")
                        .HasColumnType("integer");

                    b.Property<int>("CommercialDisposition")
                        .HasColumnType("integer");

                    b.Property<decimal>("FinancialCreditReversed")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("FrozenDisposition")
                        .HasColumnType("integer");

                    b.Property<bool>("HumanInspectionPerformed")
                        .HasColumnType("boolean");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("NewOperationalDate")
                        .HasColumnType("date");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PackagingIntact")
                        .HasColumnType("boolean");

                    b.Property<int>("PlanCreditsReversed")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PreviousOperationalDate")
                        .HasColumnType("date");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("integer");

                    b.Property<long>("PreviousVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("TemperatureControlled")
                        .HasColumnType("boolean");

                    b.Property<bool>("TraceabilityIntact")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "OrderId", "OccurredAt");

                    b.ToTable("order_lifecycle_events", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderPlanCreditAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcquisitionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CoveredAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "AcquisitionId");

                    b.HasIndex("OrganizationId", "OrderId");

                    b.HasIndex("OrganizationId", "OrderItemId");

                    b.ToTable("order_plan_credit_allocations", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Organizations.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("OrganizationId", "CorrelationId");

                    b.HasIndex("OrganizationId", "OccurredAt");

                    b.ToTable("audit_events", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("organizations", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("organization_memberships", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Organizations.PlatformUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSubject")
                        .IsUnique();

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Plans.PlanAcquisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AcquiredOn")
                        .HasColumnType("date");

                    b.Property<decimal>("BenefitAmountPerCredit")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EligibleOfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "EligibleOfferId");

                    b.ToTable("plan_acquisitions", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Plans.PlanCreditMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AcquisitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "AcquisitionId");

                    b.HasIndex("OrganizationId", "OrderId", "OrderItemId");

                    b.ToTable("plan_credit_movements", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Production.ProducibleComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompositionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DietaryMarkers")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "CompositionId");

                    b.ToTable("producible_components", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Production.ProducibleComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProducibleItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ProducibleItemId", "Version")
                        .IsUnique();

                    b.ToTable("producible_compositions", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Production.ProducibleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("producible_items", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Catalog.CatalogOffer", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Customers.CustomerDietaryRestriction", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Finance.FinancialCreditMovement", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenConfiguration", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Catalog.CatalogOffer", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OfferId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Production.ProducibleItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProducibleItemId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenLot", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenConfiguration", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FrozenConfigurationId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenStockMovement", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenLot", null)
                        .WithMany("_movements")
                        .HasForeignKey("OrganizationId", "FrozenLotId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.DailyCapacity", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.FrozenStockAllocation", b =>
                {
                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenConfiguration", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FrozenConfigurationId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenLot", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FrozenLotId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany("_frozenAllocations")
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Orders.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OrderItemId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.Order", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderCharge", b =>
                {
                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany("_charges")
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderConfirmationAudit", b =>
                {
                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany("_confirmationAudits")
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenConfiguration", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FrozenConfigurationId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ts.Api.Domain.Catalog.CatalogOffer", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OfferId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany("_items")
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Production.ProducibleItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProducibleItemId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderItemComponent", b =>
                {
                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany("_componentSnapshots")
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Orders.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OrderItemId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderLifecycleEvent", b =>
                {
                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany("_lifecycleEvents")
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderPlanCreditAllocation", b =>
                {
                    b.HasOne("Ts.Api.Domain.Plans.PlanAcquisition", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "AcquisitionId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany("_planCreditAllocations")
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Orders.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OrderItemId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Organizations.AuditEvent", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Organizations.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Plans.PlanAcquisition", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Catalog.CatalogOffer", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EligibleOfferId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Plans.PlanCreditMovement", b =>
                {
                    b.HasOne("Ts.Api.Domain.Plans.PlanAcquisition", null)
                        .WithMany("_movements")
                        .HasForeignKey("OrganizationId", "AcquisitionId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Production.ProducibleComponent", b =>
                {
                    b.HasOne("Ts.Api.Domain.Production.ProducibleComposition", null)
                        .WithMany("_components")
                        .HasForeignKey("OrganizationId", "CompositionId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Production.ProducibleComposition", b =>
                {
                    b.HasOne("Ts.Api.Domain.Production.ProducibleItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProducibleItemId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Production.ProducibleItem", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenLot", b =>
                {
                    b.Navigation("_movements");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.Order", b =>
                {
                    b.Navigation("_charges");

                    b.Navigation("_componentSnapshots");

                    b.Navigation("_confirmationAudits");

                    b.Navigation("_frozenAllocations");

                    b.Navigation("_items");

                    b.Navigation("_lifecycleEvents");

                    b.Navigation("_planCreditAllocations");
                });

            modelBuilder.Entity("Ts.Api.Domain.Plans.PlanAcquisition", b =>
                {
                    b.Navigation("_movements");
                });

            modelBuilder.Entity("Ts.Api.Domain.Production.ProducibleComposition", b =>
                {
                    b.Navigation("_components");
                });
#pragma warning restore 612, 618
        }
    }
}
