// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ts.Api.Infrastructure.Persistence;

#nullable disable

namespace Ts.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904224001_AddOrderDraftAndDailyCapacityManagement")]
    partial class AddOrderDraftAndDailyCapacityManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ts.Api.Domain.Catalog.CatalogOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FulfillmentMode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("catalog_offers", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("integer");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ProducibleItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ProducibleItemId");

                    b.HasIndex("OrganizationId", "OfferId", "ProducibleItemId", "Presentation")
                        .IsUnique();

                    b.ToTable("frozen_configurations", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<Guid>("FrozenConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("ManufacturedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "FrozenConfigurationId");

                    b.HasIndex("OrganizationId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "ExpiresOn", "ManufacturedOn", "Id");

                    b.ToTable("frozen_lots", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenStockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrozenLotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "FrozenLotId", "OccurredAt");

                    b.ToTable("frozen_stock_movements", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.DailyCapacity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LastConfigurationIdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("OperationalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservedUnits")
                        .HasColumnType("integer");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id");

                    b.HasIndex("OrganizationId", "LastConfigurationIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "OperationalDate")
                        .IsUnique();

                    b.ToTable("daily_capacities", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.FrozenStockAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrozenConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrozenLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "FrozenConfigurationId");

                    b.HasIndex("OrganizationId", "FrozenLotId");

                    b.HasIndex("OrganizationId", "OrderId");

                    b.HasIndex("OrganizationId", "OrderItemId", "FrozenLotId")
                        .IsUnique();

                    b.ToTable("frozen_stock_allocations", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmationIdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CreationIdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastModificationIdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("OperationalDate")
                        .HasColumnType("date");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ConfirmationIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "CreationIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "LastModificationIdempotencyKey")
                        .IsUnique();

                    b.ToTable("orders", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OrderId");

                    b.ToTable("order_charges", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FrozenConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FrozenPresentation")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("FulfillmentMode")
                        .HasColumnType("integer");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("OfferName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProducibleItemName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "FrozenConfigurationId");

                    b.HasIndex("OrganizationId", "OfferId");

                    b.HasIndex("OrganizationId", "OrderId");

                    b.ToTable("order_items", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("organizations", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("organization_memberships", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Organizations.PlatformUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSubject")
                        .IsUnique();

                    b.ToTable("users", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Production.ProducibleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "NormalizedName")
                        .IsUnique();

                    b.ToTable("producible_items", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Catalog.CatalogOffer", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenConfiguration", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Catalog.CatalogOffer", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OfferId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Production.ProducibleItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ProducibleItemId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenLot", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenConfiguration", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FrozenConfigurationId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenStockMovement", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenLot", null)
                        .WithMany("_movements")
                        .HasForeignKey("OrganizationId", "FrozenLotId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.DailyCapacity", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.FrozenStockAllocation", b =>
                {
                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenConfiguration", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FrozenConfigurationId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenLot", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FrozenLotId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany("_frozenAllocations")
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Orders.OrderItem", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OrderItemId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.Order", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderCharge", b =>
                {
                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany("_charges")
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenConfiguration", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "FrozenConfigurationId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ts.Api.Domain.Catalog.CatalogOffer", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "OfferId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Orders.Order", null)
                        .WithMany("_items")
                        .HasForeignKey("OrganizationId", "OrderId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Organizations.OrganizationMembership", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Organizations.PlatformUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.Production.ProducibleItem", b =>
                {
                    b.HasOne("Ts.Api.Domain.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenLot", b =>
                {
                    b.Navigation("_movements");
                });

            modelBuilder.Entity("Ts.Api.Domain.Orders.Order", b =>
                {
                    b.Navigation("_charges");

                    b.Navigation("_frozenAllocations");

                    b.Navigation("_items");
                });
#pragma warning restore 612, 618
        }
    }
}
