// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ts.Api.Infrastructure.Persistence;

#nullable disable

namespace Ts.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ts.Api.Domain.Catalog.CatalogOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FulfillmentMode")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("catalog_offers", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("integer");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("ProducibleItemId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProducibleItemId");

                    b.HasIndex("OfferId", "ProducibleItemId", "Presentation")
                        .IsUnique();

                    b.ToTable("frozen_configurations", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<Guid>("FrozenConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("ManufacturedOn")
                        .HasColumnType("date");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FrozenConfigurationId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ExpiresOn", "ManufacturedOn", "Id");

                    b.ToTable("frozen_lots", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenStockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FrozenLotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FrozenLotId", "OccurredAt");

                    b.ToTable("frozen_stock_movements", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.Production.ProducibleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("producible_items", "app");
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenConfiguration", b =>
                {
                    b.HasOne("Ts.Api.Domain.Catalog.CatalogOffer", null)
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ts.Api.Domain.Production.ProducibleItem", null)
                        .WithMany()
                        .HasForeignKey("ProducibleItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenLot", b =>
                {
                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenConfiguration", null)
                        .WithMany()
                        .HasForeignKey("FrozenConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenStockMovement", b =>
                {
                    b.HasOne("Ts.Api.Domain.FrozenStock.FrozenLot", null)
                        .WithMany("_movements")
                        .HasForeignKey("FrozenLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ts.Api.Domain.FrozenStock.FrozenLot", b =>
                {
                    b.Navigation("_movements");
                });
#pragma warning restore 612, 618
        }
    }
}
